version: '3'

services:
  data_api:
    image: dai/api
    build:
      context: express-image
    ports:
      - "9001:3000"

  apache_app:
    image: dai/apache
    build:
      context: apache-image
    ports:
      - "9000:80"
    depends_on:
      - data_api
