version: '3'

services:

  traefik:
    image: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
    ports:
      - "80:80"
      - "8080:8080"

    labels:
      - traefik.enable=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  data_api:
    image: dai/api
    build:
      context: express-image
    labels:
      - traefik.http.routers.data_api.rule=Host(`localhost`) && PathPrefix(`/api`)

    depends_on:
      - traefik

  app:
    image: dai/apache
    build:
      context: apache-image
    labels:
      - traefik.http.routers.app.rule=Host(`localhost`)
    depends_on:
      - data_api
      - traefik
