version: '3'

services:

  traefik:
    image: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
    ports:
      - "80:80"
      - "8080:8080"

    labels:
      - traefik.enable=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-web-gui:
    container_name: docker-web-gui
    image: kaive/docker-web-gui
    ports:
      - "3230:3230"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  data_api:
    image: dai/api
    build:
      context: express-image
    labels:
      - traefik.http.routers.data_api.rule=Host(`localhost`) && PathPrefix(`/api`)

    depends_on:
      - traefik

  app:
    image: dai/apache
    build:
      context: apache-image
    deploy:
      replicas: 3
    labels:
      - traefik.http.routers.app.rule=Host(`localhost`)
      - traefik.http.services.app.loadbalancer.sticky.cookie=true
      - traefik.http.services.app.loadbalancer.sticky.cookie.name=sticky-cookie
    depends_on:
      - data_api
      - traefik
